### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by cryptoquick** [paulmolluzzo/convert-css-in-js#1]
Can you change the following line to add typescript support?

https://github.com/paulmolluzzo/convert-css-in-js/blob/71a919b86fceeb4440155280d84b8500814b41fb/src/extension.js#L29

That way I don't have to switch syntaxes. Thanks for writing such a handy extension!

**Comment by paulmolluzzo** [comment]
Sure can. PRs welcome too 😉

**Comment by paulmolluzzo** [comment]
You can update the extension through the marketplace @cryptoquick!
